# Generated by Django 5.1.4 on 2024-12-16 14:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_term_years', models.PositiveIntegerField()),
                ('purpose', models.CharField(choices=[('PERSONAL', 'Personal'), ('MORTGAGE', 'Mortgage'), ('CAR', 'Car'), ('EDUCATION', 'Education'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], max_length=50)),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('card_provider', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('AMEX', 'American Express'), ('DISCOVER', 'Discover'), ('JCB', 'JCB')], default='VISA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, help_text='Amount of cryptocurrency to transact.', max_digits=20)),
                ('crypto_type', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BNB', 'Binance Coin'), ('USDT', 'Tether')], help_text='Select the type of cryptocurrency.', max_length=10)),
                ('wallet_address', models.CharField(help_text="The recipient's wallet address.", max_length=255, verbose_name='Wallet Address')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the transaction was created.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Status of the transaction.', max_length=20)),
            ],
            options={
                'verbose_name': 'Crypto Transaction',
                'verbose_name_plural': 'Withdrawal Transaction',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('occupation', models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Other', 'Other')], default='Other', max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Other', max_length=10)),
                ('residential_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('pin', models.CharField(blank=True, max_length=4, null=True)),
                ('pin_verified', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DomesticTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('beneficiary_account_name', models.CharField(max_length=255)),
                ('beneficiary_account_no', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Business', 'Business')], max_length=50)),
                ('narration', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BNB', 'Binance Coin'), ('USDT', 'Tether')], max_length=10)),
                ('network', models.CharField(choices=[('BTC', 'Bitcoin Network'), ('ETH', 'Ethereum Mainnet'), ('BSC', 'Binance Smart Chain'), ('TRC', 'Tron Network')], max_length=20)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='payment_qr_codes/')),
                ('wallet_address', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('currency', 'network', 'wallet_address')},
            },
        ),
        migrations.CreateModel(
            name='UserSecurityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_security_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="SSN must be entered in the format: '123-45-6789'.", regex='^\\d{3}-\\d{2}-\\d{4}$')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_card_front', models.FileField(blank=True, null=True, upload_to='id_card_images/')),
                ('id_card_back', models.FileField(blank=True, null=True, upload_to='id_card_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WireTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('beneficiary_account_name', models.CharField(max_length=255)),
                ('beneficiary_account_no', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('select_country', models.CharField(max_length=100)),
                ('swift_code', models.CharField(max_length=11)),
                ('routing_number', models.CharField(blank=True, max_length=9, null=True)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current Account'), ('CHECKING', 'Checking Account'), ('FIXED', 'Fixed Deposit'), ('NON_RESIDENT', 'Non Resident Account'), ('ONLINE', 'Online Banking'), ('DOMICILIARY', 'Domiciliary Account'), ('JOINT', 'Joint Account')], max_length=50)),
                ('narration_purpose', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wire_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
