# Generated by Django 5.1.4 on 2024-12-17 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCardFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('virtual_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='bank.virtualcard')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='bank.wallet')),
            ],
        ),
    ]
