# Generated by Django 5.1.4 on 2024-12-17 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_withdrawaltransaction_user_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcard',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
