# Generated by Django 5.1.4 on 2024-12-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_virtualcard_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
