# Generated by Django 5.1.4 on 2025-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcard',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Balance available on the card.', max_digits=15, null=True),
        ),
    ]
