# Generated by Django 5.1.4 on 2025-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_credittransaction_debittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
