# Generated by Django 5.1.4 on 2025-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_credittransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='debittransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
