# Generated by Django 5.1.4 on 2025-06-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_debittransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'),
        ),
    ]
