# Generated by Django 5.1.4 on 2026-07-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='is_credited',
            field=models.BooleanField(default=False),
        ),
    ]
